# Generated by Django 5.2.7 on 2025-11-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OdooInvoice',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('partner', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_date', models.CharField(blank=True, max_length=50, null=True)),
                ('amount_total', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Odoo Invoice',
                'verbose_name_plural': 'Odoo Invoices',
                'managed': True,
            },
        ),
    ]
