# Generated by Django 5.2.7 on 2025-11-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='odooinvoice',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
